server:
  port: 8086

spring:
  application:
    name: notificacion-service

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/notificacion_db?authSource=admin

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  jackson:
    serialization:
      write-dates-as-timestamps: false

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

logging:
  level:
    es.delivery.manager.notificacion: DEBUG
